name: shop_easyy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  provider: ^6.1.2
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0 # ADD THIS LINE
  go_router: ^13.2.0

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  
  # Utility
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/